"""empty message

Revision ID: a139cf1d2e90
Revises: b6ae1175e8f7
Create Date: 2020-08-27 16:17:07.683035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a139cf1d2e90'
down_revision = 'b6ae1175e8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('generes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'generes')
    # ### end Alembic commands ###
