"""empty message

Revision ID: b438c9cd975e
Revises: 4e3c604ac39d
Create Date: 2020-08-31 20:47:37.854182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b438c9cd975e'
down_revision = '4e3c604ac39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('generes', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'generes')
    # ### end Alembic commands ###
